export enum Genre {
  hiphop = 'hiphop',
  funk = 'funk',
  jazz = 'jazz',
  blues = 'blues',
  disco = 'disco',
  latin = 'latin',
  afrobeat = 'afrobeat',
  dnb = 'dnb',
  electro = 'electro',
  house = 'house',
  dubstep = 'dubstep',
  grime = 'grime',
  garage = 'garage',
  trance = 'trance',
  indie = 'indie',
  rock = 'rock',
  punk = 'punk',
  metal = 'metal',
  folk = 'folk',
  rocknroll = 'rocknroll',
  reggae = 'reggae',
  pop = 'pop',
  classical = 'classical'
}

export const genreArray = [
  'hiphop',
  'funk',
  'jazz',
  'blues',
  'disco',
  'latin',
  'afrobeat',
  'dnb',
  'electro',
  'house',
  'dubstep',
  'grime',
  'garage',
  'trance',
  'indie',
  'rock',
  'punk',
  'metal',
  'folk',
  'rocknroll',
  'reggae',
  'pop',
  'classical'
]
